### PR TITLE
Update instructions.jsp

### PR DESCRIPTION
**Pull request by Paul-Kalil**
Removed code looking up which Wildbook and replaced with Wild North Wildbook.

### CODE REVIEW

**Review by TanyaStere42 — COMMENTED** [review]
What's the benefit of doing this as direct copy rather than the configured variable? This seems like an unnecessary change.

**Comment by Paul-Kalil** [comment]
Unfortunately the configured variable is not working correctly (still calls up ACW) and I do not know enough to go fix that.

This is the easiest route for me with a lack of knowledge of the back end of WIldbook.

Thanks

Paul

**Comment by TanyaStere42** [comment]
Gotcha. If you change ln7 of `src/main/resources/bundles/context.properties`, it should address this, and you won't be trying to chase down these changes individually across the platform.

Also, `src/main/resources/bundles/commonConfiguration.properties` has a number of options that you may want to update (ln407-409 for projects, ln311-315 for relationships, ln318-322 for role types, etc etc)

**Comment by Paul-Kalil** [comment]
Thank you, appreciate the guidance. Paul

**Comment by TanyaStere42** [comment]
@Paul-Kalil I'm gonna close this PR because we discussed the changes to the properties files. It'll be easier to start a new PR editing those pages than manipulating this one to change these variables back _and_ change the properties files.

You'll still be able to access it for information, and if we decide to make the manual changes, we can always reopen it.

**Pull request closed without merging**
