### PR TITLE
582 stonely widget in react header

### PR DESCRIPTION
**Pull request by erinz2020**
fixes issue #582 
add stonely widget to react pages head

### CODE REVIEW

**Review by holmbergius — APPROVED** [review]
LGTM

**Review by naknomum — CHANGES_REQUESTED** [review]
one concern regarding some suspiciously hard-coded looking value.

**Comment by erinz2020** [comment]
> one concern regarding some suspiciously hard-coded looking value.

turned this ga_id to a variable in properties file

**Review by naknomum — APPROVED** [review]
looks good!

**Pull request merged**
