### PR TITLE
Add npm deploy for React build to local dev server

### PR DESCRIPTION
**Pull request by carllelandtaylor**
This commit codifies the steps for rebuilding the React app and copying it over to the local dev server location to make that process easier and quicker, and to remove potential developer error from the process with that codification and some environment setup checks.

```
npm run deploy-dev
```

**Changes**
- codifies the steps for rebuilding the React app and copying it over to the local dev server location to make that process easier and quicker, and to remove potential developer error from the process.
- reorganizes the frontend readme slightly to split first-time dev setup from the regular commands devs repeat

**Test Plan**
(Steps I ran to test)
1. Set up a new dev environment from scratch following the instructions in `devops/README.md` and `frontend/README.md`.
2. Used `npm run deploy-dev` instead of the manual build and copy. Verified on my local server that react/login loaded correctly and let me log in.
3. Made changes to `FrontDesk.jsx` and re-ran `npm run deploy-dev`. Refreshed the site in my browser and confirmed I saw the changes.

### CODE REVIEW

**Comment by carllelandtaylor** [comment]
I called it `deploy-dev` in case there's some other way you'd do this for prod deployments, but I'm not sure? Can rename to just `deploy` if it would be used for prod as well.

**Review by erinz2020 — COMMENTED** [review]
Hi Carl, thank you for making the build and deploy process quicker, we actually have maven doing the similar thing while deploying the _whole wildbook_, which includes backend and frontend, but for frontend developers who deploy react very frequently your PR will make this process easier.  However I had a permission denied issue while running `npm run deploy-dev`, because I was not using root when executing the command, and only root has the write access to /react. I'm wondering if there is anything we could do to solve this problem, Jon and I will also dig deeper about this, thanks


Deploying React build to development environment
Deploying to /data/tomcat10/wildbook_docker_webapps/webapps/wildbook/react
Copying build to /data/tomcat10/wildbook_docker_webapps/webapps/wildbook/react
node:internal/fs/utils:351
    throw err;
    ^

```
Error: EACCES: permission denied, unlink '/data/tomcat10/wildbook_docker_webapps/webapps/wildbook/react/images/500_background.png'
    at unlinkSync (node:fs:1881:3)
    at mayCopyFile (node:internal/fs/cp/cp-sync:215:5)
    at onFile (node:internal/fs/cp/cp-sync:210:10)
    at getStats (node:internal/fs/cp/cp-sync:179:12)
    at copyDir (node:internal/fs/cp/cp-sync:284:21)
    at onDir (node:internal/fs/cp/cp-sync:264:10)
    at getStats (node:internal/fs/cp/cp-sync:167:12)
    at copyDir (node:internal/fs/cp/cp-sync:284:21)
    at onDir (node:internal/fs/cp/cp-sync:264:10)
    at getStats (node:internal/fs/cp/cp-sync:167:12) {
  errno: -13,
  syscall: 'unlink',
  code: 'EACCES',
  path: '/data/tomcat10/wildbook_docker_webapps/webapps/wildbook/react/images/500_background.png'
}
```

**Comment by erinz2020** [comment]
ok after discussion we agreed that this permission issue is out of scope of this PR, since after changing the owner of the target folder, the code works well. Will approve and merge, thank you.

**Review by erinz2020 — APPROVED** [review]
looks good to me

**Comment by carllelandtaylor** [comment]
> After discussing, we agreed that this permission issue is out of the scope of the current PR for the following reasons:
> 
> 1. After changing the owner of the target folder, the code works as expected.
> 2. The user who unpacks the wildbook war file will also be the owner of the /react folder. In most cases, the same user will be responsible for deploying both the war file and React, so it shouldn't cause any issues.

Great! And if that turns out to be a common enough issue, now that this is in a script we could always add a check for it and log a nicer error explaining what to do.

**Pull request merged**
