### PR TITLE
Update instructions.jsp

### PR DESCRIPTION
**Pull request by Paul-Kalil**
Replace Wildbook Standard Import XLS file with WN Wildbook Standard Import XLS file

[WB_noID_upload_template_2024-03-15.xlsx](https://github.com/WildMeOrg/Wildbook/files/14716122/WB_noID_upload_template_2024-03-15.xlsx)

### CODE REVIEW

**Review by TanyaStere42 — COMMENTED** [review]
Are you trying to rename the import reference or are you trying to replace the file? To replace the file, you'll need to put your new .xlsx file in the `src/main/webapp/import` folder in place of `WildbookStandardFormat.xlsx`

**Comment by Paul-Kalil** [comment]
Great, I will do so. Thank you again for the education. :-)

**Comment by TanyaStere42** [comment]
Awesome! Glad it could help 😄

**Comment by Paul-Kalil** [comment]
Not able to upload new file to location, I think you have to do it for me as I do not have write access?  See file attached. Thanks
[WB_noID_upload_template_2024-03-15.xlsx](https://github.com/WildMeOrg/Wildbook/files/14783985/WB_noID_upload_template_2024-03-15.xlsx)

**Comment by TanyaStere42** [comment]
Hmm. Well I'll go ahead and approve and merge in the copy updates and get this file added for you then 👍

**Comment by TanyaStere42** [comment]
@Paul-Kalil https://github.com/WildMeOrg/Wildbook/commit/161e557a4e1018e8a1b37a753b7ee6f15c73241f new import is in place. Had to rename it so the system would find it

**Comment by Paul-Kalil** [comment]
Thanks.

Appreciate the help.

Regards

Paul

**Pull request merged**
