### PR TITLE
added photographer name

### PR DESCRIPTION
**Pull request by sufwankhalid1**
Added Encounter.photographer0.fullName column into Encounter Annotation Export

### CODE REVIEW

**Review by TanyaStere42 — COMMENTED** [review]
Just want to confirm, the objective is to take only the first photographer, ignoring any additional photographers in the system, for the export?

**Comment by T4Cmaureen** [comment]
Jumping in here - I wasn't aware that it's possible to have multiple photographers on a single encounter record in Wildbook so we designed this to capture one photographer full name and email address only.

**Comment by TanyaStere42** [comment]
@T4Cmaureen that's why I asked. I just confirmed that you can have multiple photographers
image

You'll need to iterate through the number of photographers (the `0` here indicates just the first photographer in the encounter: `Encounter.photographer0.Email`) to get the full list

**Comment by T4Cmaureen** [comment]
Well our users only have a single photographer per encounter so it's working as designed.

**Comment by TanyaStere42** [comment]
cool, will review with that in mind. just needed to make sure I understood what the target was

**Review by TanyaStere42 — APPROVED** [review]
confirmed feature intention is to return just first photographer; lgtm

**Pull request merged**
